# services:
#   db:
#     image: postgres:15
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 12345
#       POSTGRES_DB: sukjai
#     ports:
#       - "5432:5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data

#   backend:
#     build:
#       context: .  # ใช้ context ที่เป็น root ของโปรเจ็กต์ (คือ /Computer-Final_Project)
#       dockerfile: ./backend/Dockerfile  # ระบุ path ของ Dockerfile ที่อยู่ใน backend
#     depends_on:
#       - db
#     environment:
#       DATABASE_DSN: "user=postgres password=12345 dbname=sukjai host=db port=5432 sslmode=disable"
#     ports:
#       - "8081:8080"

#   pgadmin:
#     image: dpage/pgadmin4
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@example.com
#       PGADMIN_DEFAULT_PASSWORD: admin
#     ports:
#       - "5050:80"
#     depends_on:
#       - db

# volumes:
#   db_data:


version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: sukjai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: